### ISSUE TITLE
error[E0425]: cannot find value `SYS_ioprio_get` in crate `libc`

### ISSUE THREAD

**Issue by Martinfx** [kpcyrd/libredefender#36]
Hi,
i tried compile source code on FreeBSD 13.1 and  cargo 1.63.0 and I  have issue with missing libc
```
maxfx@ /m/S/c/libredefender (main)> cargo build
   Compiling serde_derive v1.0.144
   Compiling thiserror-impl v1.0.33
   Compiling enumflags2_derive v0.7.4
   Compiling async-trait v0.1.57
   Compiling tracing-attributes v0.1.22
   Compiling serde_repr v0.1.9
   Compiling async-recursion v0.3.2
   Compiling derivative v2.2.0
   Compiling battery v0.7.8
   Compiling ioprio v0.2.0
   Compiling bindgen v0.56.0
   Compiling structopt-derive v0.4.18
error[E0425]: cannot find value `SYS_ioprio_get` in crate `libc`
   --> /home/maxfx/.cargo/registry/src/github.com-1ecc6299db9ec823/ioprio-0.2.0/src/lib.rs:257:44
    |
257 |     let res = unsafe { libc::syscall(libc::SYS_ioprio_get, which, who) };
    |                                            ^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `SYS_ioprio_set` in crate `libc`
   --> /home/maxfx/.cargo/registry/src/github.com-1ecc6299db9ec823/ioprio-0.2.0/src/lib.rs:273:19
    |
273 |             libc::SYS_ioprio_set,
    |                   ^^^^^^^^^^^^^^ not found in `libc`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `ioprio` due to 2 previous errors
`
```

**Comment by Martinfx** [comment]
[compile_rust_libredeferender.TXT](https://github.com/kpcyrd/libredefender/files/9777105/compile_rust_libredeferender.TXT)

**Comment by kpcyrd** [comment]
One of the dependencies fails to build. you could retry with the current master at https://github.com/iliekturtles/uom but the crate doesn't seem to have any platform specific code so I'm not sure why it doesn't build on FreeBSD.

Does the project build successfully with a more recent Cargo.lock, if you run `cargo update` in advance?

**Comment by Martinfx** [comment]
This is after update packages

**Comment by iliekturtles** [comment]
As noted in https://github.com/iliekturtles/uom/issues/382 an ancient version of `uom` is being used. Using v0.30.0 resolve this error.

**Comment by Martinfx** [comment]
> As noted in [iliekturtles/uom#382](https://github.com/iliekturtles/uom/issues/382) an ancient version of `uom` is being used. Using v0.30.0 resolve this error.

good news thank you.

**Comment by kpcyrd** [comment]
This version of uom is pulled in by https://github.com/svartalf/rust-battery, it needs to be bumped there and after they released a new version it can be fixed here.

**Comment by Martinfx** [comment]
libredefender is dependent for package uom 0.21..1 and without I cannot compile this library.

**Comment by micwoj92** [comment]
> This version of uom is pulled in by https://github.com/svartalf/rust-battery, it needs to be bumped there and after they released a new version it can be fixed here.

@Martinfx I think this should be fixed now, because the battery dependency has been changed to updated fork.

**Comment by Martinfx** [comment]
I have new issue with package

```
     Running `/media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/FreeBSD-Ports/libredefender/work/target/debug/build/clamav-sys-49b0b3eb3ef33f51/build-script-build`
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=LIBCLAMAV_NO_PKG_CONFIG
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-freebsd
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_freebsd
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=HOST_PKG_CONFIG
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=LIBCLAMAV_STATIC
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=LIBCLAMAV_DYNAMIC
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-freebsd
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_freebsd
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_PATH
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-freebsd
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_freebsd
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-freebsd
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_freebsd
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
[clamav-sys 0.0.3] cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
[clamav-sys 0.0.3] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: `"pkg-config" "--libs" "--cflags" "libclamav" "libclamav >= 0.103"` did not exit successfully: exit status: 1
[clamav-sys 0.0.3] error: could not find system library 'libclamav' required by the 'clamav-sys' crate
[clamav-sys 0.0.3] 
[clamav-sys 0.0.3] --- stderr
[clamav-sys 0.0.3] Package libclamav was not found in the pkg-config search path.
[clamav-sys 0.0.3] Perhaps you should add the directory containing `libclamav.pc'
[clamav-sys 0.0.3] to the PKG_CONFIG_PATH environment variable
[clamav-sys 0.0.3] Package 'libclamav', required by 'virtual:world', not found
[clamav-sys 0.0.3] Package 'libclamav', required by 'virtual:world', not found
[clamav-sys 0.0.3] ', /media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/FreeBSD-Ports/libredefender/work/libredefender-0.6.0/cargo-crates/clamav-sys-0.0.3/build.rs:112:10
[clamav-sys 0.0.3] stack backtrace:
[clamav-sys 0.0.3]    0: rust_begin_unwind
[clamav-sys 0.0.3]    1: core::panicking::panic_fmt
[clamav-sys 0.0.3]    2: core::result::unwrap_failed
[clamav-sys 0.0.3]    3: core::result::Result<T,E>::unwrap
[clamav-sys 0.0.3]              at /usr/ports/lang/rust/work/rustc-1.65.0-src/library/core/src/result.rs:1107:23
[clamav-sys 0.0.3]    4: build_script_build::main
[clamav-sys 0.0.3]              at ./build.rs:109:5
[clamav-sys 0.0.3]    5: core::ops::function::FnOnce::call_once
[clamav-sys 0.0.3]              at /usr/ports/lang/rust/work/rustc-1.65.0-src/library/core/src/ops/function.rs:248:5
[clamav-sys 0.0.3] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `clamav-sys v0.0.3`

```

**Comment by kpcyrd** [comment]
`libclamav.pc` is missing on your system, this file is most likely in the same package that also provides the header files for libclamav.

**Comment by Martinfx** [comment]
Yes, i have clamav includes but clamav.h not found
```
/usr/local/bin/clamav-config
/usr/local/include/clamav-version.h
/usr/local/include/clamav-config.h
/usr/local/include/clamav.h
/usr/local/include/clamav-types.h
```

```
[clamav-sys 0.0.3] wrapper.h:1:10: fatal error: 'clamav.h' file not found
[clamav-sys 0.0.3] wrapper.h:1:10: fatal error: 'clamav.h' file not found, err: true
[clamav-sys 0.0.3] thread 'main' panicked at 'Unable to generate bindings: ()', /media/ST3000DM007-1WY10G_ZTT0SM4Q_p1/code/FreeBSD-Ports/libredefender/work/libredefender-e9fac36c9d5b45de021f4b22c6d71c604bc44ae8/cargo-crates/clamav-sys-0.0.3/build.rs:66:10
[clamav-sys 0.0.3] stack backtrace:
[clamav-sys 0.0.3]    0: rust_begin_unwind
[clamav-sys 0.0.3]    1: core::panicking::panic_fmt
[clamav-sys 0.0.3]    2: core::result::unwrap_failed
[clamav-sys 0.0.3]    3: core::result::Result<T,E>::expect
[clamav-sys 0.0.3]              at /usr/ports/lang/rust/work/rustc-1.65.0-src/library/core/src/result.rs:1064:23
[clamav-sys 0.0.3]    4: build_script_build::generate_bindings
[clamav-sys 0.0.3]              at ./build.rs:62:5
[clamav-sys 0.0.3]    5: build_script_build::main
[clamav-sys 0.0.3]              at ./build.rs:115:5
[clamav-sys 0.0.3]    6: core::ops::function::FnOnce::call_once
[clamav-sys 0.0.3]              at /usr/ports/lang/rust/work/rustc-1.65.0-src/library/core/src/ops/function.rs:248:5
[clamav-sys 0.0.3] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `clamav-sys v0.0.3`

```

**Comment by kpcyrd** [comment]
How did you resolve `libclamav.pc` missing? This file is supposed to point to the correct header file location, on my system `libclamav.pc`  looks like this:

```
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib
includedir=/usr/include

Name: libclamav
Description: A GPL virus scanner
Version: 0.105.1
Libs: -L${libdir} -lclamav
Libs.private:
Cflags: -I${includedir}

```

**Comment by Martinfx** [comment]
i resolved missing "libclamav.pc" so i instal "pkg install clamav" and  "/usr/local/libdata/pkgconfig/libclamav.pc"
